In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Dataset/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [9]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [10]:
for i in df:
  if df[i].dtype=='int' or df[i].dtype=='float':
    print(df[i].value_counts())
    print('_________________________________________________')

Id
1      1
95     1
97     1
98     1
99     1
      ..
51     1
52     1
53     1
54     1
150    1
Name: count, Length: 150, dtype: int64
_________________________________________________
SepalLengthCm
5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64
_________________________________________________
SepalWidthCm
3.0    26
2.8    14
3.2    13
3.1    12
3.4    12
2.9    10
2.7     9
2.5     8
3.5     6
3.3     6
3.8     6
2.6     5
2.3     4
3.7     3
2.4     3
2.2     3
3.6     3
3.9     2
4.4     1
4.0     1
4.1     1
4.2     1
2.0     1
Name: count, dtype: int64
_________________________________________________
PetalLengthCm
1.5    14
1.4    12
5.1     8
4.5   

In [11]:
object_type=[]    #creating empty list
for i in df:      #iterating through the df
  if df[i].dtype=='object': #if the datatype is object
    object_type.append(i)

In [12]:
object_type

['Species']

In [14]:
from sklearn.preprocessing import LabelEncoder
dict1={}                  #creating empty dict
for i in object_type:     #iterating through the list of columns
  dict1[i]=LabelEncoder() #creating seperate objects for each column
  df[i]=dict1[i].fit_transform(df[i])

In [15]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [16]:
dict1['Species'].inverse_transform([1])

array(['Iris-versicolor'], dtype=object)

In [17]:
dict1['Species'].inverse_transform([0])

array(['Iris-setosa'], dtype=object)

In [18]:
dict1['Species'].inverse_transform([2])

array(['Iris-virginica'], dtype=object)

In [19]:
x=df.drop(columns=['Species'])
y=df['Species']

In [20]:
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [21]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [22]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler  #calling MinMaxScaler and StandardScaler class from sklearn.preprocessing
minmax=MinMaxScaler()                           #creating an object
x_scaled=minmax.fit_transform(x)

In [24]:
scaler=StandardScaler()
x_scaled_new=scaler.fit_transform(x)
x_scaled_new.max()
x_scaled_new.min()

-2.438987252491841

In [25]:
x_scaled.shape

(150, 5)

In [26]:
y.shape

(150,)

In [27]:
from sklearn.model_selection import train_test_split    #train_test_split is a function and not a class
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.3,random_state=2)

In [28]:
from sklearn.neighbors import KNeighborsClassifier      #importing kneighbour classifier from sklearn
model=KNeighborsClassifier()                            #creating an object to train using knc, there are many parameters in this one of them is n neighbours which is by default set to 5
model.fit(x_train,y_train)

KNeighborsClassifier()

In [29]:
x_test[0]

array([0.04026846, 0.08333333, 0.58333333, 0.06779661, 0.08333333])

In [30]:
model.predict(x_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1,
       0])

In [31]:
model.predict(x_test[0].reshape((1,5)))

array([0])

In [32]:
y_pred=model.predict(x_test)

In [33]:
y_test.values

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1,
       0])

In [34]:
y_pred

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1,
       0])

In [35]:
from sklearn.metrics import accuracy_score    #importing accuracy score function from sklearn library which has metrics module
print(accuracy_score(y_test,y_pred))    #gives the accuracy by comparing y_test(actual correct values) with y_pred(predicted values), each value in y_test is compared to the corresponding value in y_pred
print(f"Accuracy:{round(accuracy_score(y_test,y_pred)*100)}")

1.0
Accuracy:100


In [36]:
from sklearn.svm import SVC #from sklearn library svm module we import svc(support vector classifier) class\
model=SVC()   #creating an obj
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
model.score(x_train,y_train)

1.0


1.0

In [37]:
from sklearn.metrics import confusion_matrix    #importing confusion matrix
print(confusion_matrix(y_test,y_pred))

[[17  0  0]
 [ 0 15  0]
 [ 0  0 13]]


In [38]:
from sklearn.metrics import classification_report   #import classification_report from sklearn metrics
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

